[package]
name = "fs"
version = "0.1.0"
publish.workspace = true
license.workspace = true
edition.workspace = true

[lib]
path = "src/fs.rs"

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
serde.workspace = true
